Update to syn 2
jbaublitz/getset pull request #93
Opened 2024-06-28 22:04 UTC by noamteyssier

Addresses #92 

I tried my hand at updating the syn API to v2.

Also some minor refactoring to some of the larger/complex functions like `parse_visibility` and `has_prefix_attr` to make simpler (at least to my eye). 

Passes all tests, and happy to make edits you see fit.

---
- update version 0.1.2 -> 0.2.0
- update syn 1 -> 2
- set explicit version numbers in dependencies
- convert syn api from 1 -> 2
- refactor `parse_visibility` to use two helper functions
- refactor `has_prefix_attr` to use simplified closure
- streamline getters, setters, etc functions to avoid redundant let statements

2024-08-20 21:41 UTC, jbaublitz commented
Hi @noamteyssier, I apologize for the delay. I will take a look at this within the next week and provide a review.

2024-09-08 21:13 UTC, jayvdb approved these changes

2024-09-09 11:29 UTC, jbaublitz requested changes
I think overall this looks good. There are some stylistic requests, but if you get those fixed up, I'm going to do some testing on this and then will merge it!

2024-09-09 11:29 UTC, jbaublitz commented on src/generate.rs
> +                if let Lit::Str(s) = &expr_lit.lit {
This seems like it could use `expr_to_string()` instead of reimplementing it.

2024-09-09 11:29 UTC, jbaublitz commented on src/generate.rs
> +                    return s.value().split_whitespace().any(|v| v == "with_prefix");
We should decide either on `split_whitespace()` or `split(' ')`. I think using both could cause confusion.

2024-09-09 11:29 UTC, jbaublitz commented on src/generate.rs
> +        .map_or(false, |meta| meta_has_prefix(&meta));
I think this could use the same pattern as below (`.as_ref().map(..., meta_has_prefix)`.

2024-09-09 11:29 UTC, jbaublitz commented on src/lib.rs
> +                    last.or_else(|| collected.into_iter().next())
I think pop makes more sense here rather than constructing an intermediate iterator just to return one item.

2024-09-09 18:30 UTC, jbaublitz commented
@noamteyssier Thanks for the submission! Because I'm getting pinged about a number of things related to this upgrade in addition to the upgrade itself, I'm going to take over and just add on the changes in a separate commit so that you get proper attribution for your contribution.

2024-09-09 22:09 UTC, closed without merging