Add 'WithSetters' proc_macro_derive, change version to 0.2.0
jbaublitz/getset pull request #97
Opened 2024-09-14 16:18 UTC by andeya

```rust
GenMode::SetWith => {
    quote! {
        #(#doc)*
        #[inline(always)]
        #visibility fn #fn_name(mut self, val: #ty) -> Self {
            self.#field_name = val;
            self
        }
    }
}
```

`fn_name` is `with_{field_name}`

2024-09-15 08:47 UTC, jbaublitz commented
Hi @andeya. As you might know, I took over this crate a few years ago and haven't had much time to work on it. I'm trying to catch up on the PRs and issues at the moment and should have time to review this tomorrow. Just so I understand, is this aiming to do the same thing as #84?

2024-09-15 12:00 UTC, andeya commented
@jbaublitz Yes, it is the same requirement, but the implementation is more in line with Rust specifications and more complete and reliable than that of #84.

2024-09-20 16:49 UTC, andeya commented
@jbaublitz After waiting for a long time without result, I have independently published it to [getset2](https://crates.io/crates/getset2).
cc https://github.com/jbaublitz/getset/pull/84

2025-01-15 15:03 UTC, musjj commented
@jbaublitz 

Hey, any chance this PR can get some love?

There has been a few attempts at this in the past (https://github.com/jbaublitz/getset/pull/87, https://github.com/jbaublitz/getset/pull/84), but I think this PR has the most idiomatic implementation.

2025-01-16 15:15 UTC, jbaublitz commented
@musjj I have finally been catching up on a backlog of issues over on my other crate I maintain, neli. I just got a release out for that containing some bug fixes that I've been sitting on for a while, so I'm going to shift my focus to getset and try to make my way backwards through the pull requests and then the issues.

2025-01-17 23:00 UTC, jbaublitz requested changes
I've reviewed the code and just have one comment. Other than that, this looks good and I'd be willing to merge and put out a new release.

2025-01-19 23:00 UTC, jbaublitz commented
@andeya I tried to run cargo semver-checks on this crate, but apparently it doesn't work with proc-macro crates. I believe that this is just a feature, so I'm going to release it as 0.1.4. Please let me know if you have any objections.

2025-01-20 15:05 UTC, jbaublitz commented
Superseded by #102

2025-01-20 15:05 UTC, closed without merging